title: Robby Klein
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robbyk.com" # the base hostname & protocol for your site, e.g. http://example.com
email: hirobbyk@gmail.com
twitter: itsrobbyk
github:  robbyklein
analytics: UA-133769752-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed